name: Automated lint & code formatting checks
on: [push]
jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v2
              with:
                  node-version: '20.x'
                  registry-url: https://npm.pkg.github.com/
            - name: 'Create env file'
              run: |
                  touch .env
                  echo VITE__APP_ENV=${{ secrets.APP_ENV }} >> .env
                  echo VITE__API_ENDPOINT=${{ secrets.API_ENDPOINT }} >> .env
                  echo VITE__REACT_QUERY_DEBUGGING=${{ secrets.REACT_QUERY_DEBUGGING }} >> .env
                  cat .env
            - name: Install NPM dependencies
              run: npm ci
            - name: Check formatting
              run: npm run format:check
            - name: Check lint
              run: npm run lint
            - name: Build the app
              run: npm run build
              env:
                  CI: true
